#! /bin/csh
#
# $Id: ALT-MAILER,v 1.2 1994-11-23 01:46:12 jik Exp $
#
# From: tengi@Princeton.EDU
#
#  xrn.mailer:     /u/tengi/bin/xrn-mh-mailer
#
cat > /tmp/mail.${USER}.$$
send /tmp/mail.${USER}.$$
exit 0
